/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InvitationCodeRouteImport } from './routes/invitation.$code'
import { Route as AppListesListIdRouteImport } from './routes/_app/listes.$listId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InvitationCodeRoute = InvitationCodeRouteImport.update({
  id: '/invitation/$code',
  path: '/invitation/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListesListIdRoute = AppListesListIdRouteImport.update({
  id: '/listes/$listId',
  path: '/listes/$listId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/invitation/$code': typeof InvitationCodeRoute
  '/listes/$listId': typeof AppListesListIdRoute
}
export interface FileRoutesByTo {
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/invitation/$code': typeof InvitationCodeRoute
  '/': typeof AppIndexRoute
  '/listes/$listId': typeof AppListesListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/invitation/$code': typeof InvitationCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/listes/$listId': typeof AppListesListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bienvenue' | '/connexion' | '/invitation/$code' | '/listes/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/bienvenue' | '/connexion' | '/invitation/$code' | '/' | '/listes/$listId'
  id:
    | '__root__'
    | '/_app'
    | '/bienvenue'
    | '/connexion'
    | '/invitation/$code'
    | '/_app/'
    | '/_app/listes/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BienvenueRoute: typeof BienvenueRoute
  ConnexionRoute: typeof ConnexionRoute
  InvitationCodeRoute: typeof InvitationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invitation/$code': {
      id: '/invitation/$code'
      path: '/invitation/$code'
      fullPath: '/invitation/$code'
      preLoaderRoute: typeof InvitationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/listes/$listId': {
      id: '/_app/listes/$listId'
      path: '/listes/$listId'
      fullPath: '/listes/$listId'
      preLoaderRoute: typeof AppListesListIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppListesListIdRoute: typeof AppListesListIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppListesListIdRoute: AppListesListIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BienvenueRoute: BienvenueRoute,
  ConnexionRoute: ConnexionRoute,
  InvitationCodeRoute: InvitationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
